from . import role
from . import user_connection
from . import admin_connection
from . import user_start_evaluation
from . import user_assessment
from . import user_last_assessment
from . import user_end_assessment
from . import user_change_assessment
from . import user_again_assessment
from . import confirmation
