from . import user_info
from . import main_admin_add_admin
from . import main_admin_delete_admin
from . import confirmation
from . import page_switcher
from . import admin_session
from . import admin_confirmation_candidate_name
from . import competencies
from . import profiles
from . import user_assessment_comp
