from . import role
from . import text_recognizer
from . import user_connection
from . import admin_connection
from . import user_start_evaluation
from . import user_assessment
from . import user_last_assessment
from . import user_end_assessment
from . import user_finish
from . import user_change_assessment
from . import user_again_assessment
from . import confirmation
from . import admin_create_session
from . import admin_successful_creation_session
from . import admin_end_session
from . import admin_choosing_actions_competencies
from . import admin_create_competencies
from . import admin_delete_competencies
from . import admin_change_competencies
from . import admin_change_competencies_name_or_description
from . import admin_change_competencies_name
from . import admin_change_competencies_description
from . import admin_choosing_actions_profile
from . import admin_delete_profile
from . import admin_change_profile
from . import admin_change_profile_name_or_competencies
from . import admin_change_profile_name
from . import admin_change_profile_competencies
from . import admin_create_profile
