from . import confirmation_add
from . import main_admin_add_admin
from . import main_admin_delete_admin
from . import change_competence
from . import confirmation_change_competence
from . import confirmation_delele
from . import confirmation_candidate_name
from . import confirmation_delete_profile
from . import confirmation_delete_session
from . import user_grading_competencies
from . import user_grade
